import type { Metadata } from "next";
import "./globals.css";
import {Quicksand, Fredoka} from "next/font/google";
import Image from "next/image";
import localFont from "next/font/local";
import Navbar from "@/app/components/navbar";

const sfProRounded = localFont({
    src: [
        { path: "../public/fonts/SFProRounded-Regular.woff2", weight: "400" },
        { path: "../public/fonts/SFProRounded-Bold.woff2", weight: "700" },
        { path: "../public/fonts/SFProRounded-SemiBold.woff2", weight: "600" },
        { path: "../public/fonts/SFProRounded-Medium.woff2", weight: "500" },
        { path: "../public/fonts/SFProRounded-Black.woff2", weight: "900" },

    ],
    variable: "--font-sf",
    display: "swap",
});

const sfCompactRounded = localFont({
    src: [
        { path: "../public/fonts/SFCompactRounded-Regular.ttf", weight: "400" },
        { path: "../public/fonts/SFCompactRounded-Bold.ttf", weight: "700" },
        { path: "../public/fonts/SFCompactRounded-SemiBold.ttf", weight: "600" },
        { path: "../public/fonts/SFCompactRounded-Medium.ttf", weight: "500" },
        { path: "../public/fonts/SFCompactRounded-Black.ttf", weight: "900" },
    ],
    variable: "--font-sf-compact",
    display: "swap",
})

const quicksand = Quicksand({
    subsets: ['latin'],
    variable: '--font-quicksand',
})
const fre = Fredoka({
    subsets: ['latin'],
    variable: '--font-fre',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${sfProRounded.variable} ${quicksand.variable} ${fre.variable} ${sfCompactRounded.variable}`} >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
