import type { Metadata } from "next";
import "./globals.css";
import {Quicksand, Fredoka, Poppins} from "next/font/google";
import localFont from "next/font/local";
import Navbar from "@/app/components/navbar";
import Footer from "@/app/components/footer";
import {cookies} from "next/headers";
import Compare from "@/app/components/compare";
const sfProRounded = localFont({
    src: [
        { path: "../public/fonts/SFProDisplay-Regular.woff2", weight: "400" },
        { path: "../public/fonts/SFProDisplay-Bold.woff2", weight: "700" },
        { path: "../public/fonts/SFProDisplay-Semibold.woff2", weight: "600" },
        { path: "../public/fonts/SFProDisplay-Medium.woff2", weight: "500" },
        { path: "../public/fonts/SFProDisplay-Black.woff2", weight: "900" },

    ],
    variable: "--font-sf",
    display: "swap",
});

const sfCompactRounded = localFont({
    src: [
        { path: "../public/fonts/SFCompactRounded-Regular.ttf", weight: "400" },
        { path: "../public/fonts/SFCompactRounded-Bold.ttf", weight: "700" },
        { path: "../public/fonts/SFCompactRounded-Semibold.ttf", weight: "600" },
        { path: "../public/fonts/SFCompactRounded-Medium.ttf", weight: "500" },
        { path: "../public/fonts/SFCompactRounded-Black.ttf", weight: "900" },
    ],
    variable: "--font-sf-compact",
    display: "swap",
})

const quicksand = Quicksand({
    subsets: ['latin'],
    variable: '--font-quicksand',
})
const fre = Fredoka({
    subsets: ['latin'],
    variable: '--font-fre',
})
const pop = Poppins({
    weight: ["100","200","300","400","500","600","700","800","900"],
    subsets: ['latin'],
    style: "normal",
    variable: '--font-pop'
})
export const metadata: Metadata = {
  title: "em Trung đồ án",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body  className={`${sfProRounded.variable} ${quicksand.variable} ${fre.variable} ${sfCompactRounded.variable} ${pop.variable} flex items-center flex-col`} >
      <Navbar/>
        {children}
      <Compare/>
      <Footer/>
      </body>
    </html>
  );
}
